# Generated by Django 4.2.23 on 2025-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
