# Generated by Django 4.2.15 on 2025-10-30 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthdayapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-date'], 'verbose_name_plural': 'parties'},
        ),
        migrations.AlterModelOptions(
            name='photolike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='party',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partyphoto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partyphoto',
            name='image',
            field=models.ImageField(upload_to='party_photos/'),
        ),
        migrations.AlterField(
            model_name='partyphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
