# Generated by Django 4.2.15 on 2025-11-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthdayapi', '0003_alter_party_options_alter_photolike_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbookentry',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_book_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='message',
            field=models.TextField(help_text='The guest book message'),
        ),
        migrations.AddIndex(
            model_name='guestbookentry',
            index=models.Index(fields=['-created_at'], name='birthdayapi_created_bb539f_idx'),
        ),
        migrations.AddIndex(
            model_name='guestbookentry',
            index=models.Index(fields=['party', '-created_at'], name='birthdayapi_party_i_06199c_idx'),
        ),
    ]
