# Generated by Django 4.2.15 on 2025-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0004_remove_guestbookentry_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='name',
            field=models.CharField(blank=True, help_text='Display name for the guest book entry', max_length=255),
        ),
    ]
