# Generated by Django 4.2.15 on 2025-11-01 10:33

from django.db import migrations


def populate_name_field(apps, schema_editor):
    """Populate the name field for existing guest book entries"""
    GuestBookEntry = apps.get_model('birthdayapi', 'GuestBookEntry')
    
    for entry in GuestBookEntry.objects.all():
        # Use the author's first and last name if available
        if entry.author.first_name or entry.author.last_name:
            name_parts = []
            if entry.author.first_name:
                name_parts.append(entry.author.first_name)
            if entry.author.last_name:
                name_parts.append(entry.author.last_name)
            entry.name = ' '.join(name_parts)
        else:
            # Fallback to username if no name is available
            entry.name = entry.author.username
        entry.save()


def reverse_populate_name_field(apps, schema_editor):
    """Reverse migration - clear name field"""
    GuestBookEntry = apps.get_model('birthdayapi', 'GuestBookEntry')
    GuestBookEntry.objects.update(name='')


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0005_guestbookentry_name'),
    ]

    operations = [
        migrations.RunPython(populate_name_field, reverse_populate_name_field),
    ]
