# Generated by Django 4.2.15 on 2025-11-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0006_auto_20251101_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartyTimelineEvent',
        ),
    ]
