# Generated by Django 4.2.15 on 2025-11-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0007_delete_partytimelineevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
