# Generated by Django 4.2.15 on 2025-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0008_delete_weatherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenmoPayment',
        ),
    ]
