# Generated by Django 4.2.8 on 2025-11-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0010_partytimelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Personal', max_length=100)),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(blank=True, max_length=200)),
                ('option_4', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.PositiveIntegerField(help_text='Index of correct answer (0-3)')),
                ('points', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trivia_questions', to='birthdayapi.party')),
            ],
            options={
                'verbose_name': 'Trivia Question',
                'verbose_name_plural': 'Trivia Questions',
                'ordering': ['category', 'question'],
            },
        ),
    ]
